import numpy as np
# Demonstration of numpy.reshape with comments and many examples
# Original array of 10 elements
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Reshape to 5 rows and inferred columns (-1)
print("x.reshape(5, -1) ->")
print(x.reshape(5, -1))
# Recreate original array to show independent examples
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Reshape to 1 row (1 x 10)
print("x.reshape(1, -1) ->")
print(x.reshape(1, -1))
# Reshape to 2 rows (2 x 5)
print("x.reshape(2, -1) ->")
print(x.reshape(2, -1))
# Reshape to 5 rows again (5 x 2)
print("x.reshape(5, -1) ->")
print(x.reshape(5, -1))
# Reshape to 10 rows (10 x 1)
print("x.reshape(10, -1) ->")
print(x.reshape(10, -1))
# --- Ten additional examples below ---
# Example 1: array of 12 elements reshaped to (3, 4)
a1 = np.arange(1, 13)
print("a1 (1..12) reshape (3,4) ->")
print(a1.reshape(3, 4))
# Example 2: same 12 elements reshaped to (4, 3)
a2 = np.arange(1, 13)
print("a2 (1..12) reshape (4,3) ->")
print(a2.reshape(4, 3))
# Example 3: 16 elements reshaped to (4, 4)
a3 = np.arange(1, 17)
print("a3 (1..16) reshape (4,4) ->")
print(a3.reshape(4, 4))
# Example 4: 15 elements reshaped to (5, 3)
a4 = np.arange(1, 16)
print("a4 (1..15) reshape (5,3) ->")
print(a4.reshape(5, 3))
# Example 5: 20 elements reshaped to (5, 4)
a5 = np.arange(1, 21)
print("a5 (1..20) reshape (5,4) ->")
print(a5.reshape(5, 4))
# Example 6: 6 elements reshaped to (2, 3)
a6 = np.array([10, 20, 30, 40, 50, 60])
print("a6 reshape (2,3) ->")
print(a6.reshape(2, 3))
# Example 7: 8 elements reshaped to (2, 4)
a7 = np.arange(8)
print("a7 (0..7) reshape (2,4) ->")
print(a7.reshape(2, 4))
# Example 8: 9 elements reshaped to (3, 3)
a8 = np.arange(1, 10)
print("a8 (1..9) reshape (3,3) ->")
print(a8.reshape(3, 3))
# Example 9: 18 elements reshaped to (3, 6)
a9 = np.arange(1, 19)
print("a9 (1..18) reshape (3,6) ->")
print(a9.reshape(3, 6))
# Example 10: 24 elements reshaped to (6, 4)
a10 = np.arange(1, 25)
print("a10 (1..24) reshape (6,4) ->")
print(a10.reshape(6, 4))
# Additional illustrative examples showing -1 inference and order parameter
# Example 11: use -1 to infer columns for 12 elements into 3 rows
b1 = np.arange(12)
print("b1 reshape (3, -1) ->")
print(b1.reshape(3, -1))
# Example 12: reshape with one dimension as -1 and the other explicit
b2 = np.arange(12)
print("b2 reshape (-1, 6) ->")
print(b2.reshape(-1, 6))
# Example 13: reshape to a single column (n,1)
b3 = np.arange(5)
print("b3 reshape (5, 1) ->")
print(b3.reshape(5, 1))
# Example 14: reshape to a single row (1,n)
b4 = np.arange(5)
print("b4 reshape (1, 5) ->")
print(b4.reshape(1, 5))
# Example 15: reshape and then transpose to swap axes
c1 = np.arange(12)
reshaped_c1 = c1.reshape(3, 4)
print("c1 reshape (3,4) then transpose ->")
print(reshaped_c1.T)
# Example 16: reshape using order='F' (column-major) vs default 'C' (row-major)
d1 = np.arange(1, 7)
print("d1 reshape (2,3) default order ->")
print(d1.reshape(2, 3))
print("d1 reshape (2,3) order='F' ->")
print(d1.reshape(2, 3, order='F'))
# Example 17: reshape a 1D array into a 3D array
e1 = np.arange(24)
print("e1 reshape (2,3,4) ->")
print(e1.reshape(2, 3, 4))
# Example 18: reshape with negative dimension in multi-axis (one -1 allowed)
f1 = np.arange(30)
print("f1 reshape (5, -1, 3) ->")
print(f1.reshape(5, -1, 3))
# Example 19: reshape then flatten back to 1D using ravel()
g1 = np.arange(12)
g1_reshaped = g1.reshape(3, 4)
print("g1_reshaped ->")
print(g1_reshaped)
print("g1_reshaped.ravel() ->")
print(g1_reshaped.ravel())
# Example 20: reshape with copy vs view behavior (note: reshape may return view)
h1 = np.arange(6)
h1_reshaped = h1.reshape(2, 3)
print("h1 original ->")
print(h1)
print("h1_reshaped ->")
print(h1_reshaped)
# Modify the reshaped view to show it may affect the original (if view)
h1_reshaped[0, 0] = 999
print("After modifying h1_reshaped[0,0] = 999")
print("h1 ->")
print(h1)
print("h1_reshaped ->")
print(h1_reshaped)
# Restore original for cleanliness